name = "bill-splitter-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
MAX_PARTICIPANTS = "50"
MAX_EXPENSES = "500"
MAX_TOTAL_SPLITS = "10000"
SPLIT_EXPIRY_HOURS = "24"

[[d1_databases]]
binding = "DB"
database_name = "bill-splitter-db"
database_id = "3f6b5ac0-5ed2-4724-938d-528b3fbcf353"

[dev]
port = 3001
